### ISSUE TITLE
Missing bug in FireMatches

### ISSUE THREAD

**Issue by charlesfranciscodev** [Morriar/csg_debug_2017#1]
There is a missing bug in FireMatches.

When reading the latitude in `parseLocation` the index should be 1 instead of 0.

according to the README:
`radius:`: with `long(0),lat(1):radius` to specify a radius search by location

The error can be found
in [src/firematches/profiles/GPSLocation.java](https://github.com/Morriar/csg_debug_2017/blob/master/bugs/FireMatches/PUBLIC/src/firematches/profiles/GPSLocation.java)
```java
public static GPSLocation parseLocation(String location) throws LocationFormatException {
    String[] parts = location.split(","); // that makes us really sad :(
    if(parts.length != 2) {
        throw new LocationFormatException(location);
    }
    // Double lat = Double.parseDouble(parts[0]); (incorrect index)
    Double lat = Double.parseDouble(parts[1]); 
    Double lon = Double.parseDouble(parts[0]);
    return new GPSLocation(lon, lat);
}
```

**Comment by Morriar** [comment]
Good catch, this was an unplanned bug.

I'm therefore more impressed by the teams who fixed FireMatches during the competition!

**Comment by Morriar** [comment]
I'm not sure about the course of actions to fix this issue.

1. Should I fix the code in PRIVATE and regen the tests so the new players who want to test the competition by themselves can play with a *less bugged* bugged version?

2. Or should I leave it as it was during the CSGames?
